# Generated by Django 2.0.6 on 2018-08-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pin',
            name='categories',
            field=models.ManyToManyField(related_query_name='pins', to='pins.Category'),
        ),
    ]
