# Generated by Django 2.0.6 on 2018-08-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20180804_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ['-created']},
        ),
    ]
